### ISSUE TITLE
Kan man se auktionerna? [U7-29ST13]   2

### ISSUE THREAD

**Issue by BharathiHarsha** [totor0/Team-3#39]
Man kan se alla auktionerna men man kan inte sortera enligt Slutar Snarast, Nyligen tillagda, Billigast först,Dyrast först....etc. Sorting function is not working.

**Comment by klautia** [comment]
Det blir rätt när jag trycker på slutar snarast/nyligen tillagda/ osv när jag går in på alla auktioner

Dock går det **inte** att trycka sig från tex, nyligen tillagda till billigast, då blir det ingen uppdatering.

Jag behöver alltså klicka mig in i någon annan del i hemsidan för att sedan gå tillbaka till alla auktioner och därefter trycka på hur jag vill att den ska sorteras
