### ISSUE TITLE
kan man skrolla ner hur mycket som helst utan lagg? [US25-26T42]

### ISSUE THREAD

**Issue by totor0** [totor0/Team-3#48]
Hemsidan är responsiv men ej snabb, självklart förståeligt under beta fas. Något som tar lite längre tid än normalt är spalten där budet, nedräkning och lägg bud är.

**Comment by klautia** [comment]
Samma vid Internet explorer, budet, nedräkning och läggbud tar en tid att komma upp men hemsidan är responsiv

**Comment by klautia** [comment]
Samma gäller Mozilla, tar ca två till tre sekunder att komma upp

**Comment by klautia** [comment]
Via Android tar det ca 2-5 sek innan det lägg upp bud osv kommer upp
